server:
  port: 8081

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cc
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1

logging:
  config: classpath:log4j2.xml
